const MOVE_MS=1800,HOLD_MS=2400;
const state={map:null,objectives:[],index:0,timer:null,lockTimer:null,paused:false,selected:null,mapReady:false};
const els={console:document.getElementById("console"),map:document.getElementById("map"),markerLayer:document.getElementById("marker-layer"),list:document.getElementById("objective-list"),reticule:document.getElementById("reticule"),pulse:document.getElementById("pulse"),leader:document.getElementById("leader"),leaderLine:document.getElementById("leader-line"),intel:document.getElementById("intel-panel"),pause:document.getElementById("pause-cycle"),reset:document.getElementById("reset-view")};
async function loadObjectives(){const r=await fetch("data/objectives.json",{cache:"no-store"});if(!r.ok)throw new Error("Objective data unavailable");return r.json()}
function formatCoord(v,p,n){const h=v>=0?p:n,a=Math.abs(v),d=Math.floor(a),mf=(a-d)*60,m=Math.floor(mf),s=Math.round((mf-m)*60);return `${String(d).padStart(2,"0")}° ${String(m).padStart(2,"0")}′ ${String(s).padStart(2,"0")}″ ${h}`}
function allBounds(){return L.latLngBounds(state.objectives.map(o=>[o.lat,o.lon])).pad(window.innerWidth<=900?.16:.12)}
function fitIsland(){if(!state.map)return;state.map.invalidateSize({pan:false});const mobile=window.innerWidth<=900;state.map.fitBounds(allBounds(),{paddingTopLeft:L.point(mobile?26:76,mobile?86:66),paddingBottomRight:L.point(mobile?26:76,mobile?58:66),animate:false,maxZoom:11});updatePositions(true)}
function initialiseMap(){state.map=L.map("map",{zoomControl:false,attributionControl:false,dragging:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false,tap:false,touchZoom:false,fadeAnimation:true,zoomAnimation:false,preferCanvas:true});const imagery=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:18,crossOrigin:true,keepBuffer:4});const roads=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}",{maxZoom:18,opacity:.22,crossOrigin:true,keepBuffer:4});let ready=false;imagery.on("tileload",()=>{if(ready)return;ready=true;state.mapReady=true;fitIsland();startCycle()});imagery.addTo(state.map);roads.addTo(state.map);fitIsland();state.map.on("moveend zoomend resize",()=>updatePositions(true));setTimeout(()=>{if(!state.selected)startCycle()},1800)}
function project(o){if(state.mapReady&&state.map){const p=state.map.latLngToContainerPoint([o.lat,o.lon]);return{x:p.x,y:p.y}}const r=els.map.getBoundingClientRect(),b=state.objectives.reduce((a,o)=>({minLat:Math.min(a.minLat,o.lat),maxLat:Math.max(a.maxLat,o.lat),minLon:Math.min(a.minLon,o.lon),maxLon:Math.max(a.maxLon,o.lon)}),{minLat:90,maxLat:-90,minLon:180,maxLon:-180});return{x:((o.lon-b.minLon)/(b.maxLon-b.minLon))*r.width,y:(1-(o.lat-b.minLat)/(b.maxLat-b.minLat))*r.height}}
function createUI(){els.markerLayer.innerHTML="";els.list.innerHTML="";state.objectives.forEach(o=>{const m=document.createElement("button");m.className="marker";m.dataset.type=o.behaviour.type;m.type="button";m.addEventListener("click",()=>selectObjective(o,true));els.markerLayer.appendChild(m);o.marker=m;const item=document.createElement("button");item.className="objective-item";item.type="button";item.innerHTML=`<span>${String(o.sequence).padStart(2,"0")}</span><span>${o.shortName}</span>`;item.addEventListener("click",()=>selectObjective(o,true));els.list.appendChild(item);o.item=item});requestAnimationFrame(()=>updatePositions(false))}
function setReticule(o,animate=true){const p=project(o);if(!animate){const t=els.reticule.style.transition;els.reticule.style.transition="none";els.reticule.style.left=`${p.x}px`;els.reticule.style.top=`${p.y}px`;els.pulse.style.left=`${p.x}px`;els.pulse.style.top=`${p.y}px`;void els.reticule.offsetWidth;els.reticule.style.transition=t}else{els.reticule.style.left=`${p.x}px`;els.reticule.style.top=`${p.y}px`;els.pulse.style.left=`${p.x}px`;els.pulse.style.top=`${p.y}px`}}
function updatePositions(force=false){state.objectives.forEach(o=>{const p=project(o);o.marker.style.left=`${p.x}px`;o.marker.style.top=`${p.y}px`});if(state.selected)setReticule(state.selected,!force);if(!els.intel.hidden)drawLeader(state.selected)}
function clearEffect(){els.console.dataset.effect="none"}
function applyEffect(o){clearEffect();if(o.behaviour.effect==="glitch")els.console.dataset.effect="classified"}
function drawLeader(o){if(!o||window.innerWidth<=900){els.leader.classList.remove("active");return}const p=project(o),mr=els.map.getBoundingClientRect(),pr=els.intel.getBoundingClientRect(),right=els.intel.classList.contains("dock-right"),endX=right?pr.left-mr.left:pr.right-mr.left,endY=pr.top-mr.top+54,elbowX=right?Math.min(endX-45,p.x+90):Math.max(endX+45,p.x-90);els.leaderLine.setAttribute("points",`${p.x},${p.y} ${elbowX},${p.y} ${elbowX},${endY} ${endX},${endY}`);els.leader.classList.add("active")}
function lockOn(o,open=false){applyEffect(o);els.reticule.classList.remove("searching");els.reticule.classList.add("locked");els.pulse.className="pulse";if(o.behaviour.pulse==="slow")els.pulse.classList.add("slow");void els.pulse.offsetWidth;els.pulse.classList.add("active");state.objectives.forEach(x=>{x.marker.classList.toggle("active",x.id===o.id);x.item.classList.toggle("active",x.id===o.id)});document.getElementById("coord-lat").textContent=formatCoord(o.lat,"N","S");document.getElementById("coord-lon").textContent=formatCoord(o.lon,"E","W");document.getElementById("sequence-readout").textContent=`${String(o.sequence).padStart(2,"0")} / ${String(state.objectives.length).padStart(2,"0")}`;if(open)openPanel(o)}
function selectObjective(o,open=false){clearEffect();clearTimeout(state.timer);clearTimeout(state.lockTimer);state.selected=o;els.reticule.classList.remove("locked");els.reticule.classList.add("searching");setReticule(o,true);state.lockTimer=setTimeout(()=>lockOn(o,open),MOVE_MS)}
function cycle(){if(state.paused)return;const o=state.objectives[state.index];state.index=(state.index+1)%state.objectives.length;selectObjective(o,false);state.timer=setTimeout(cycle,MOVE_MS+HOLD_MS)}
function startCycle(){if(state.selected||!state.objectives.length)return;state.selected=state.objectives[0];state.index=1;setReticule(state.selected,false);lockOn(state.selected,false);state.timer=setTimeout(cycle,HOLD_MS)}
function openPanel(o){state.paused=true;clearTimeout(state.timer);const p=project(o),w=els.map.getBoundingClientRect().width,dock=o.behaviour.panelDock;els.intel.classList.toggle("dock-right",dock==="right"||(dock==="auto"&&p.x<w/2));document.getElementById("intel-number").textContent=`OBJECTIVE ${String(o.sequence).padStart(2,"0")}`;document.getElementById("intel-name").textContent=o.name;document.getElementById("intel-status").textContent=o.status;document.getElementById("intel-classification").textContent=o.classification;document.getElementById("intel-description").textContent=o.description;document.getElementById("intel-link").href=o.page;els.intel.hidden=false;els.pause.textContent="RESUME CYCLE";requestAnimationFrame(()=>drawLeader(o))}
function closePanel(){els.intel.hidden=true;els.leader.classList.remove("active");clearEffect();state.paused=false;els.pause.textContent="PAUSE CYCLE";state.timer=setTimeout(cycle,700)}
document.getElementById("close-panel").addEventListener("click",closePanel);els.pause.addEventListener("click",()=>{state.paused=!state.paused;els.pause.textContent=state.paused?"RESUME CYCLE":"PAUSE CYCLE";if(state.paused){clearTimeout(state.timer);clearTimeout(state.lockTimer)}else state.timer=setTimeout(cycle,350)});els.reset.addEventListener("click",()=>{clearEffect();fitIsland()});
(async()=>{state.objectives=await loadObjectives();createUI();initialiseMap();window.addEventListener("resize",fitIsland);window.addEventListener("orientationchange",()=>setTimeout(fitIsland,250))})();
